import fs from 'node:fs';
import {createHash} from 'node:crypto';
const tag=process.argv[2]||'verify',data=JSON.parse(fs.readFileSync(`docs/burst113-${tag}-distribution.json`));
const pct=x=>(x*100).toFixed(2)+'%',signed=x=>(x>=0?'+':'')+Math.round(x).toLocaleString('en-US'),n=x=>Math.round(x).toLocaleString('en-US');
const settings=data.settings.map(({stopped,unlimited,...r})=>{const {values:a,...s}=stopped,{values:b,...u}=unlimited;return {...r,stopped:s,unlimited:u};});
const summary={version:113,status:'2000pt plus AT Lv5; higher setting-specific entry frequency',measurement:{gamesPerTrial:30000,trialsPerSetting:settings[0].report.trials,fullGames:settings.reduce((s,r)=>s+r.report.games,0),rtp:'total actual payout / total actual BET; free replay debit is zero',win:'final net strictly positive',complete:'first session net +10000pt; all sessions are simulated to 30000G before cutting the actual-rule prefix'},sourceHashes:Object.fromEntries(['nova-art.js','nova-flow.js','nova-normal.js','nova-balance.js','research/burst112/production-model.mjs'].map(f=>[f,createHash('sha256').update(fs.readFileSync(f)).digest('hex')])),settings};
fs.writeFileSync('docs/burst113-summary.json',JSON.stringify(summary,null,2)+'\n');
let md=`# ＋2,000pt・AT Lv.5案：30,000Gの出玉分布と勝率\n\n成功時の上乗せを8,000ptから2,000ptへ変更。成功後のAT Lv.5は維持し、チャレンジの突入抽選を設定ごとに約1.5〜2.4倍へ増やして機会を分散。初期150pt、3G合計成功50%、1AT1回、通常ATのLv.1〜3、特化の保証は維持する。\n\n先行試算で頻度を単純に4倍にしたところ、設定6の＋10,000pt到達率は36.5%（30,000G×200試行）になったため採用していない。元の到達目標2/4/6/10/15/20%付近を優先し、設定別の頻度を調整した。\n\n## 集計条件\n\n各設定 **30,000G×${n(settings[0].report.trials)}試行**、計 **${n(summary.measurement.fullGames)}G**。先行試算とは別の乱数シードで検証。設定2・3は最初の1,000試行で到達率が低かったため頻度を再調整し、さらに別のシードで各1,000試行を実施。他の設定は最初の検証値を採用。\n\n- 出玉分布＝終了時の差枚（実払い出し−実BET）。累計払い出しではない。\n- 勝率＝差枚がプラスで終わった試行の割合。±0は勝ちに含めない。\n- 本体条件＝初回差枚＋10,000ptでCOMPLETE、未到達なら30,000Gで終了。到達Gの払い出しで最大14ptの超過があり得る。\n- 停止なし＝COMPLETE後も30,000Gまで継続する比較用集計。全試行をまず最後まで計算し、本体条件は途中時点で切り出す。\n- 到達率＝30,000G以内に一度でも差枚＋10,000ptに達した割合。停止なしの終了差枚が＋10,000pt以上の割合とは異なる。\n- 機械割の推定値＝総払い出し÷総実BET。設定変更後からの有限期間推定であり、無限期間の定常値ではない。\n- 95%区間は勝率・到達率がWilson区間、機械割が試行単位の比率推定区間。\n\n## コンプリート停止あり（最大30,000G）\n\n|設定|勝率|勝率95%区間|平均差枚|中央値|＋10,000pt到達率|到達率95%区間|機械割推定|\n|---|---:|---|---:|---:|---:|---|---:|\n`;
for(const r of settings)md+=`|${r.setting}|${pct(r.stopped.winRate)}|${r.stopped.winRateCI.map(pct).join('〜')}|${signed(r.stopped.mean)}pt|${signed(r.stopped.median)}pt|${pct(r.report.completeRate)}|${r.report.completeCI.map(pct).join('〜')}|${pct(r.report.stoppedRtp.value)}|\n`;
md+='\n設定6の到達率は20.1%で目標の約20%付近。設定2は2.7%で目標の約4%より低く、設定5も13.2%で目標の約15%を下回った。これらを目標達成済みとは扱わない。各設定1,000試行のため標本誤差があり、単一の値に合わせて頻度を再調整し続けてはいない。\n';
md+=`\n![コンプリート停止ありの差枚分布](burst113-${tag}-stopped-distribution.png)\n\n## 差枚帯の割合（コンプリート停止あり）\n\n|差枚帯|設定1|設定2|設定3|設定4|設定5|設定6|\n|---|---:|---:|---:|---:|---:|---:|\n`;
for(let i=0;i<settings[0].stopped.bands.length;i++)md+=`|${settings[0].stopped.bands[i].label}|${settings.map(r=>pct(r.stopped.bands[i].count/r.stopped.trials)).join('|')}|\n`;
md+=`\n## 停止なし・固定30,000G\n\n|設定|勝率|平均差枚|中央値|5%点|95%点|機械割推定|機械割95%区間|\n|---|---:|---:|---:|---:|---:|---:|---|\n`;
for(const r of settings)md+=`|${r.setting}|${pct(r.unlimited.winRate)}|${signed(r.unlimited.mean)}pt|${signed(r.unlimited.median)}pt|${signed(r.unlimited.p05)}pt|${signed(r.unlimited.p95)}pt|${pct(r.report.rtp.value)}|${r.report.rtp.ci.map(pct).join('〜')}|\n`;
md+=`\n![停止なしの差枚分布](burst113-${tag}-unlimited-distribution.png)\n\n## 旧8,000pt版との比較\n\n旧版も各設定30,000G×1,000試行。本体と同じコンプリート停止で比較。乱数シードが異なるため、値の差には標本誤差も含まれる。\n\n|設定|旧版の到達率|今回の到達率|旧版の機械割推定|今回の機械割推定|\n|---|---:|---:|---:|---:|\n`;
const oldTrial=JSON.parse(fs.readFileSync('docs/burst112-summary.json')).trial;
for(const r of settings){const old=oldTrial[r.setting-1];md+=`|${r.setting}|${pct(old.completeRate)}|${pct(r.report.completeRate)}|${pct(old.stoppedRtp)}|${pct(r.report.stoppedRtp.value)}|\n`;}
md+=`\n## 分散させた確率\n\n突入率は「対象小役の成立時の抽選」。以下は強ノヴァ時の値で、弱スイカは0.05倍、強スイカ0.5倍、チャンス目A/B0.2倍、弱ノヴァ0.1倍。通常時・特化中・ルーレット・挑戦後等は抽選対象外。\n\n|設定|旧版|今回|倍率|実測チャレンジ回数|実測成功回数|\n|---|---:|---:|---:|---:|---:|\n`;
const oldEntry=[.0006,.00115,.00165,.0027,.0036,.0052];
for(const r of settings){const e=r.report.entry[r.setting-1];md+=`|${r.setting}|${(oldEntry[r.setting-1]*100).toFixed(3)}%|${(e*100).toFixed(3)}%|${(e/oldEntry[r.setting-1]).toFixed(2)}倍|${r.report.burstAttempts}|${r.report.burstWins}|\n`;}
md+=`\n成功率は全設定共通で3G以内50%（毎G約20.63%）。成功した時点の残りptへ2,000を加算する。残り150ptなら2,150ptとなり、以後の払い出しで減る。固定8,000ptを減らした分、その後のLv.5での上乗せ・継続が出玉を左右する。既に付与済みの残りptは更新で減らさない。\n\n## 爆発成功ATの払い出し\n\n以下は測定中に終了まで観測できたATのみの統計。長いATは30,000G時点で未終了になりやすいため、真の平均として扱わない。AT開始前のBIG払い出しは含めない。\n\n|設定|終了を観測|未終了|平均払い出し|中央値|90%点|\n|---|---:|---:|---:|---:|---:|\n`;
for(const r of settings){const b=r.report.burst;md+=`|${r.setting}|${b.completed}|${b.censored}|${n(b.mean)}pt|${n(b.p50)}pt|${n(b.p90)}pt|\n`;}
md+=`\n## 検証と再現\n\n- 試算：\`node research/burst113/run.mjs batch research/burst113/verify-config.json\`\n- 設定2・3の最終条件：\`node research/burst113/run.mjs batch research/burst113/refine-config.json\`\n- 分布：\`node research/burst113/distribution.mjs ${tag}\`\n- グラフ：\`python research/burst113/plot-distribution.py ${tag}\`\n- 本体一致：\`node research/burst113/verify-production.mjs ${tag}\`\n- 採用データの対応：\`research/burst113/selected-data.json\`（設定1・4・5・6はverify、2・3はrefine）。生データは各項目のfile参照。\n- 旧版コアは\`research/burst113/baseline112/\`に保存。試算はそのコアの加算ptと突入確率だけを置換して実行。通常時・ボーナス・特化の抽選は変更していない。\n\nこれはゲーム内の出玉設計の試算。前回の日本の型式試験基準との比較で確認した、短期・中期の出玉上限や実機構造の課題を解決したという検証ではない。\n`;
fs.writeFileSync('docs/burst113-report.md',md);
console.log(JSON.stringify(settings.map(r=>({s:r.setting,win:r.stopped.winRate,mean:r.stopped.mean,median:r.stopped.median,reach:r.report.completeRate,stopRtp:r.report.stoppedRtp.value,unlimitedWin:r.unlimited.winRate,unlimitedRtp:r.report.rtp.value}))));
