import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const h=fs.readFileSync('jag.html','utf8'),fn=n=>h.match(new RegExp('  function '+n+'\\([^]*?\\n  }'))[0];
function setup(win,playing=false){let callback,rolls=0,spins=0,played=0;const failures=[],forward=[];const nodes={machine:{dataset:{}},spinBtn:{},resultText:{}};
const c=vm.createContext({autoPlay:false,queueAutoStep(){c.autoQueued=true;},autoDelayMs:()=>100,NovaResults:{transition:()=>null},playOneShotSound(src){failures.push(src);},normalState:{flow:{zone:'ouma',oumaPending:true}},debugFastSpinActive:false,settings:{novaArt:{}},stopBtns:[{}],reels:[0,1,2].map(()=>({style:{setProperty(){}}})),document:{getElementById:id=>nodes[id]},$:id=>nodes[id],clearTimeout(){},setTimeout(fn,ms){callback=fn;c.delay=ms;return 1},clearOumaReverseAudio(){c.oumaReverseAudio=null;},stopAutoPlay(){},stopSpeedToBonus(){},persistState(){},updateDisplay(){},isCompleteTrialLocked:()=>false,NovaArt:{prepareBet(v){rolls++;return {...v,oumaPending:false,zero:win}}},spin(options){spins++;c.spinOptions=options;},Audio:function(){this.play=()=>{played++;return Promise.resolve()};this.pause=()=>{};},performance:{now:()=>0},sfxOutputVolumeForSource:()=>1,SFX_OUTPUT_SCALE:1,NovaReelMotion:{startSynced(...args){forward.push(args);},start(){},clear(){},clearAll(){}},REEL_STRIPS:[[],[],[]],cellHtml(){},setReelColumn(){},reelWindowFromTopIndex(){}});
vm.runInContext('let oumaChainTimer=null;var oumaFailDimTimer=null;var oumaPresentation=null,oumaIntroAudio=null,oumaStoppedTops=[0,0,0],oumaReverseAudio=null;'+['clearOumaPresentation','scheduleOumaZeroChain','resolveOumaChallenge'].map(fn).join('\n'),c);
if(playing)c.oumaReverseAudio={paused:false,ended:false};return {c,nodes,failures,forward,advance:()=>callback(),rolls:()=>rolls,spins:()=>spins,played:()=>played};}
test('stopped reels hold until reverse audio ends, then accept BET',()=>{const t=setup(true,true);t.c.scheduleOumaZeroChain();assert.equal(t.nodes.machine.dataset.oumaFreeze,'hold');assert.equal(t.nodes.spinBtn.disabled,true);t.c.resolveOumaChallenge();assert.equal(t.rolls(),0);t.c.oumaReverseAudio.onended();assert.equal(t.nodes.machine.dataset.oumaFreeze,'bet');assert.equal(t.nodes.spinBtn.disabled,false);});
test('successful BET retains intro then starts zero spin after 4000ms',()=>{const t=setup(true);t.c.scheduleOumaZeroChain();t.c.resolveOumaChallenge();t.c.resolveOumaChallenge();assert.equal(t.rolls(),1);assert.equal(t.played(),1);assert.equal(t.spins(),0);assert.equal(t.c.delay,4000);t.advance();assert.equal(t.spins(),1);});
test('failed BET plays intro and lifts before starting one real game without another BET',()=>{const t=setup(false);t.c.scheduleOumaZeroChain();t.c.resolveOumaChallenge();t.c.resolveOumaChallenge();assert.equal(t.rolls(),1);assert.equal(t.spins(),0);assert.equal(t.played(),1);assert.equal(t.c.delay,4000);assert.equal(t.nodes.machine.dataset.oumaFreeze,'lift');t.advance();assert.equal(t.spins(),1);assert.equal(t.c.spinOptions.oumaFailed,true);assert.equal(t.forward.length,0);assert.equal(t.nodes.machine.dataset.oumaFreeze,'');});
test('reset invalidates delayed challenge result',()=>{const t=setup(true);t.c.scheduleOumaZeroChain();t.c.resolveOumaChallenge();t.c.clearOumaPresentation();t.advance();assert.equal(t.spins(),0);});
test('AUTO is retained and queued only once reverse audio ends',()=>{const t=setup(true,true);t.c.autoPlay=true;t.c.stopAutoPlay=()=>{throw Error('AUTO stopped');};t.c.scheduleOumaZeroChain();assert.equal(t.c.autoQueued,undefined);t.c.oumaReverseAudio.onended();assert.equal(t.c.autoQueued,true);assert.equal(t.c.autoPlay,true);});
test('AUTO waits during hold and lift and only resolves the BET stage',()=>{const t=setup(true);Object.assign(t.c,{autoPlay:true,bonusEndBgmPlaying:false,bonusConfirmSoundPlaying:false,canPlayCompleteTrial:()=>true,autoPollDelayMs:()=>100});vm.runInContext(fn('runAutoStep'),t.c);t.c.scheduleOumaZeroChain();t.c.oumaPresentation.stage='hold';t.c.runAutoStep();assert.equal(t.rolls(),0);t.c.oumaPresentation.stage='bet';t.c.runAutoStep();assert.equal(t.rolls(),1);assert.equal(t.c.delay,4000);t.c.runAutoStep();assert.equal(t.rolls(),1);t.advance();assert.equal(t.spins(),1);});
