import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';const ctx=vm.createContext({});for(const f of ['nova-art.js','nova-balance.js','nova-flow.js','nova-normal.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const a=ctx.NovaArt;
test('raw ura means before guarantee are 100/100/150 with mean-one tiers and unbiased rounding',()=>{for(const [zone,baseMean,target]of [['sosuke',20,100],['toto',30,100],['urapi',40,150]]){let sum=0;for(let i=0;i<1200;i++)sum+=a.swingAward(baseMean,{zone,awardTier:4,ura:true},()=>(i+.5)/1200);assert.ok(Math.abs(sum/1200-target*5.5)<1e-10);}});
test('Sora final-game nebula resets ten games and grants no set by itself',()=>{for(const id of ['sora','ura_sora']){let s=a.startZone(a.enter(),id);s.zoneLeft=1;const t=a.step(s,{},()=>.99,'NEBULA');assert.equal(t.result,'NEBULA');assert.equal(t.flow.zoneLeft,10);assert.equal(t.flow.zone,'sora');assert.equal(t.flow.sets,'1');assert.equal(t.flow.zero,false);assert.match(t.message,/10G/);}});
test('Sora reset-inclusive raw means before guarantee are 3 and 6 direct sets',()=>{const c=a.config();for(const [ura,target]of [[false,3],[true,6]]){const r=a.soraRates({ura},c);assert.ok(Math.abs(r.seven*a.resetGamesMean(r.reset)-target)<1e-10);assert.ok(r.seven+r.reset<1);}assert.equal(a.resetGamesMean(0),10);});
test('Ouma last-game hit waits for BET and free NOVA chains without consuming G',()=>{let s={...a.startZone(a.enter(),'ouma',{oumaGames:1},()=>.8),awardTier:4};let t=a.step(s,{},()=>.99,'WEAK_NOVA');assert.equal(t.flow.zone,'ouma');assert.equal(t.flow.zoneLeft,0);assert.equal(t.flow.oumaPending,true);assert.equal(t.flow.award,'182');assert.equal(t.flow.remaining,'275');s=a.normalize(JSON.parse(JSON.stringify(t.flow)));s=a.prepareBet(s,{},()=>.1);assert.equal(s.zero,true);t=a.step(s,{},()=>.1);assert.equal(t.oumaFreeze,true);assert.equal(t.result,'WEAK_NOVA');assert.equal(t.internalBonus,null);assert.equal(t.flow.zoneLeft,0);assert.equal(t.flow.remaining,'275');assert.equal(t.flow.award,'265');assert.equal(t.flow.oumaPending,true);s=a.prepareBet(t.flow,{},()=>.99);assert.equal(s.zone,'');assert.equal(s.remaining,'540');assert.equal(s.zero,false);const again=a.prepareBet(s,{},()=>0);assert.equal(again.remaining,'540');});
test('Ouma failed BET continuation resumes the next paid zone G',()=>{let s={...a.startZone(a.enter(),'ouma',{},()=>0),awardTier:4};s=a.step(s,{},()=>.99,'WEAK_NOVA').flow;assert.equal(s.zoneLeft,4);s=a.prepareBet(s,{},()=>.99);assert.equal(s.zero,false);const t=a.step(s,{},()=>.99);assert.equal(t.flow.zoneLeft,3);assert.equal(t.oumaFreeze,false);});
test('Ouma chain-inclusive raw means before guarantee are 100 and 300',()=>{const c=a.config();for(const [ura,target,mult]of [[false,100,1],[true,300,3]]){const f=a.oumaFreezeRate({ura},c);const mean=c.oumaGames*c.oumaHit*36.5*mult*(1-f)/(1-f);assert.ok(Math.abs(mean-target)<1e-10);}});
test('live and simulator prepare BET before deciding whether to consume a game',()=>{const h=fs.readFileSync('jag.html','utf8');const f=h.match(/function countTotalSpinIfNeeded\([^]*?\n  }/)[0];assert.ok(f.indexOf('NovaArt.prepareBet')<f.indexOf('normalState.flow?.zero'));assert.match(h,/if\(resolved.oumaFreeze\)showOverlay/);assert.match(fs.readFileSync('scripts/simulate-normal.mjs','utf8'),/flow=a.prepareBet\(flow,c,rng\);if\(!flow.zero\)bet\(\)/);});

test('Giru adds 24G after three successes to initial 100pt with two paid games',()=>{let s=a.startZone(a.enter(),'giru'),paid=0;const run=r=>{if(!s.zero)paid++;const t=a.step(s,{},()=>r);s=a.normalize(JSON.parse(JSON.stringify(t.flow)));return t;};run(.5);assert.equal(s.giruBase,3);assert.equal(s.award,'117');assert.equal(s.zero,false);for(let i=0;i<3;i++)assert.equal(run(0).reverse,true);assert.equal(s.award,'236');assert.equal(s.giruContinues,3);assert.equal(paid,2);run(.99);assert.equal(s.remaining,'511');assert.equal(s.zone,'');assert.equal(paid,2);});

test('live Ouma free BET charges neither pt nor total game count',()=>{const h=fs.readFileSync('jag.html','utf8'),f=name=>h.match(new RegExp('  function '+name+'\\([^]*?\\n  }'))[0];vm.runInContext('const A_TYPE_MODE=true,SPIN_COST=3;const session={active:false},settings={novaArt:{}},stats={totalSpins:10,totalFee:30},normalState={flow:{phase:"art",zone:"ouma",zoneLeft:0,remaining:"50",award:"30",oumaPending:true}};const clearCzReelBlackout=()=>{};const recordSlumpPoint=()=>{},updateCompleteTrialState=()=>{};'+f('countTotalSpinIfNeeded')+f('chargeSpinCost')+';Math.random=()=>.1;countTotalSpinIfNeeded();chargeSpinCost();',ctx);assert.equal(vm.runInContext('stats.totalFee',ctx),30);assert.equal(vm.runInContext('stats.totalSpins',ctx),10);assert.equal(vm.runInContext('normalState.flow.zero',ctx),true);});
