import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const ctx=vm.createContext({});for(const f of ['nova-art.js','nova-balance.js','nova-flow.js','nova-normal.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const n=ctx.NovaNormal,a=ctx.NovaArt;
test('all six ceilings award BIG at exact normal/CZ boundary',()=>{for(let i=0;i<6;i++){const state={mode:n.modes[i],games:n.ceilings[i]-2};assert.equal(n.spin(state,{phase:'normal'},1,{scale:0},()=>.99,'MISS').internalBonus,null);state.games++;for(const flow of [{phase:'normal'},{phase:'cz',remaining:1,success:true}])assert.equal(n.spin(state,flow,1,{scale:0},()=>.99,'MISS').internalBonus.kind,'BIG');}});
test('hundreds parity and high state multiply CZ probability',()=>{for(const games of [0,98,99,198,199,298,399,499]){assert.equal(n.favored({mode:'通常A',games}),Math.floor((games+1)/100)%2===0);assert.equal(n.favored({mode:'通常B',games}),Math.floor((games+1)/100)%2!==0);}assert.equal(n.multiplier({mode:'通常A',games:0,level:'high'}),4);});
test('rare states upgrade, misses and replays downgrade, impurity caps and survives',()=>{for(const role of Object.keys(n.rare)){const s=n.advance({impurity:99},role,{phase:'normal'},{},()=>0);assert.equal(s.level,'high');assert.equal(s.impurity,100);}for(const r of ['MISS','REPLAY'])assert.equal(n.advance({level:'high'},r,{phase:'normal'},{},()=>0).level,'low');assert.equal(n.claim({impurity:99}).sets,0);const claimed=n.claim({impurity:100},false,()=>0);assert.equal(claimed.sets,1);assert.equal(claimed.zones[0],'urapi');assert.equal(claimed.state.impurity,0);assert.equal(n.claim(claimed.state).sets,0);});
test('freeze offers exactly three equal outcomes and stacks reserved zones with impurity',()=>{for(let i=0;i<3;i++){const c=n.claim({},true,()=> (i+.5)/3);assert.equal(c.zones[0],['giru','sora','ouma'][i]);assert.equal(c.sets,1);}const c=n.claim({impurity:100},true,()=>0);assert.equal(c.zones.length,2);let flow=a.afterBonus(null,{},c.sets);flow.queuedZones=c.zones;flow=a.normalize(JSON.parse(JSON.stringify(flow)));const spin=a.step(flow,{},()=>.99);assert.equal(spin.flow.zone,'urapi');assert.equal(spin.flow.queuedZones[0],'giru');});
test('heaven preparation transitions to heaven and all transition rows sum to100',()=>{for(const row of n.transitions)assert.equal(row.reduce((x,y)=>x+y),100);assert.equal(n.afterBonus({mode:'天国準備',impurity:55},()=>0).mode,'天国A');assert.equal(n.afterBonus({mode:'天国準備'},()=>.99).mode,'天国B');assert.equal(n.afterBonus({impurity:55}).impurity,55);});
test('new payout schedule is mode-independent',()=>{for(const r of ['BELL','STRONG_BELL'])assert.equal(n.pay(r),8);for(const r of ['WEAK_SUICA','STRONG_SUICA'])assert.equal(n.pay(r),6);assert.equal(n.pay('CHANCE_A'),0);assert.ok(n.rare.CHANCE_A.cz>n.rare.CHANCE_B.cz);});
test('live ART rare roles pay correctly and chance A has a stronger BIG draw than B',()=>{
 const opts={big:.12,zone:0};
 const next=role=>a.step(a.enter(),opts,()=>.13,role);
 assert.equal(next('CHANCE_A').internalBonus.kind,'BIG');assert.equal(next('CHANCE_B').internalBonus,null);
 for(const role of ['WEAK_SUICA','STRONG_SUICA','STRONG_BELL'])assert.equal(next(role).result,role);
 let seed=333,paid=0;const rng=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<200000;i++)paid+=n.pay(a.step(a.enter(),{big:0,zone:0},rng).result);assert.ok(Math.abs(paid/200000-5.5)<.03);
});
