import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const h=fs.readFileSync('jag.html','utf8'),fn=n=>h.match(new RegExp('  function '+n+'\\([^]*?\\n  }'))[0];
function setup(win,playing=false){let callback,rolls=0,spins=0,played=0;const nodes={machine:{dataset:{}},spinBtn:{},resultText:{}};
const c=vm.createContext({normalState:{flow:{zone:'ouma',oumaPending:true}},debugFastSpinActive:false,settings:{novaArt:{}},stopBtns:[{}],reels:[0,1,2].map(()=>({style:{setProperty(){}}})),document:{getElementById:id=>nodes[id]},$:id=>nodes[id],clearTimeout(){},setTimeout(fn,ms){callback=fn;c.delay=ms;return 1},clearOumaReverseAudio(){c.oumaReverseAudio=null;},stopAutoPlay(){},stopSpeedToBonus(){},persistState(){},updateDisplay(){},isCompleteTrialLocked:()=>false,NovaArt:{prepareBet(v){rolls++;return {...v,oumaPending:false,zero:win}}},spin(){spins++;},Audio:function(){this.play=()=>{played++;return Promise.resolve()};this.pause=()=>{};},performance:{now:()=>0},sfxOutputVolumeForSource:()=>1,SFX_OUTPUT_SCALE:1,NovaReelMotion:{start(){},clear(){},clearAll(){}},REEL_STRIPS:[[],[],[]],cellHtml(){},setReelColumn(){},reelWindowFromTopIndex(){}});
vm.runInContext('let oumaChainTimer=null;var oumaPresentation=null,oumaIntroAudio=null,oumaStoppedTops=[0,0,0],oumaReverseAudio=null;'+['clearOumaPresentation','scheduleOumaZeroChain','resolveOumaChallenge'].map(fn).join('\n'),c);
if(playing)c.oumaReverseAudio={paused:false,ended:false};return {c,nodes,advance:()=>callback(),rolls:()=>rolls,spins:()=>spins,played:()=>played};}
test('stopped reels hold until reverse audio ends, then accept BET',()=>{const t=setup(true,true);t.c.scheduleOumaZeroChain();assert.equal(t.nodes.machine.dataset.oumaFreeze,'hold');assert.equal(t.nodes.spinBtn.disabled,true);t.c.resolveOumaChallenge();assert.equal(t.rolls(),0);t.c.oumaReverseAudio.onended();assert.equal(t.nodes.machine.dataset.oumaFreeze,'bet');assert.equal(t.nodes.spinBtn.disabled,false);});
for(const win of [true,false])test('BET plays intro and waits 1500ms before outcome: '+win,()=>{const t=setup(win);t.c.scheduleOumaZeroChain();t.c.resolveOumaChallenge();t.c.resolveOumaChallenge();assert.equal(t.rolls(),1);assert.equal(t.played(),1);assert.equal(t.spins(),0);assert.equal(t.c.delay,1500);assert.equal(t.nodes.machine.dataset.oumaFreeze,'lift');t.advance();assert.equal(t.spins(),win?1:0);assert.equal(t.nodes.machine.dataset.oumaFreeze,win?'':'fail');});
test('reset invalidates delayed challenge result',()=>{const t=setup(true);t.c.scheduleOumaZeroChain();t.c.resolveOumaChallenge();t.c.clearOumaPresentation();t.advance();assert.equal(t.spins(),0);});
