import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
for(const f of ['nova-art.js','nova-balance.js'])vm.runInThisContext(fs.readFileSync(f,'utf8'));const a=NovaArt;
const sequence=values=>()=>{assert.ok(values.length);return values.shift();};
test('threshold includes the proposed award and remains exact for large saved points',()=>{assert.equal(a.zoneAwardFactor('1999'),1);assert.equal(a.zoneAwardFactor('1950',50),.01);assert.equal(a.zoneAwardFactor('2000'),.01);assert.equal(a.zoneAwardFactor('999999999999999999999999'),.01);});
test('ladder crossing fails before displaying a winning symbol and settles earned award',()=>{let s={...a.startZone(a.enter(),'ura_giru',{},()=>0),ladderRevealed:true,ladderIndex:3,award:'1500',zoneLeft:1};let t=a.step(s,{},sequence([.1,0,0,.5]));assert.equal(t.result,'MISS');assert.equal(t.flow.remaining,'1775');assert.equal(t.flow.zone,'');t=a.step(s,{},sequence([.1,0,0,.005]));assert.equal(t.flow.remaining,'2275');});
test('seven crossing is rare but not capped; extension is reduced after threshold',()=>{const s={...a.startZone(a.enter(),'ura_sora'),award:'1950',zoneLeft:1};let t=a.step(s,{},sequence([0,.3,0,.5]));assert.equal(t.result,'MISS');assert.equal(t.flow.remaining,'2225');t=a.step(s,{},sequence([0,.3,0,.005]));assert.equal(t.flow.remaining,'2275');assert.equal(a.zoneRules({...s,award:'2000'}).reset,.0025);assert.equal(a.zoneRules(s).reset,.25);});
test('paid Nova crossing is suppressed; committed free spin still pays and next freeze is reduced',()=>{const s={...a.startZone(a.enter(),'ura_ouma'),award:'1900',zoneLeft:1};let t=a.step(s,{},sequence([0,0,0,.5]));assert.equal(t.result,'MISS');assert.equal(t.flow.remaining,'2175');assert.equal(a.oumaFreezeRate(s,a.defaults),.006500000000000001);t=a.step({...s,zero:true},{},()=>0);assert.equal(t.result,'SUPER_NOVA');assert.equal(t.flow.award,'2100');assert.equal(t.flow.zero,false);});
test('threshold persists across reload and resets for a newly started zone',()=>{const s=JSON.parse(JSON.stringify({...a.startZone(a.enter(),'sora'),award:'2300'}));assert.equal(a.zoneAwardFactor(a.normalize(s).award),.01);assert.equal(a.startZone(a.settleZone(s),'sora').award,'0');});
test('turning off tail multiplier recovers legacy exact means',()=>{const saved=a.zoneTailControl.factor;a.zoneTailControl.factor=1;try{assert.ok(Math.abs(NovaBalance.zoneMean('ura_sora')-1545.9300411522636)<1e-8);assert.ok(Math.abs(NovaBalance.zoneMean('ura_ouma')-1700)<1e-8);assert.ok(Math.abs(NovaBalance.zoneMean('ura_giru')-1549.86808)<1e-8);}finally{a.zoneTailControl.factor=saved;}});
