import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const ctx=vm.createContext({});for(const f of ['nova-art.js','nova-balance.js','nova-flow.js','nova-normal.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);const a=ctx.NovaArt;
test('all twelve forced zones exist, persist and finish with correct names',()=>{assert.equal(a.zoneIds.length,12);for(const id of a.zoneIds){let t=a.step(a.enter(),{},()=>.99,'ZONE_'+id);assert.equal(t.flow.ura,id.startsWith('ura_'));assert.match(t.message,new RegExp(a.zoneName(id)));let s=a.normalize(JSON.parse(JSON.stringify(t.flow))),g=0;while(s.zone&&g++<20)s=a.step(s,{},()=>.99).flow;assert.equal(s.zone,'');assert.ok(BigInt(s.remaining)>=50n);}});
test('normal and guaranteed entries promote at exactly 3%, forced normal remains normal',()=>{for(const zone of Object.keys(a.names)){assert.equal(a.startZone(a.enter(),zone,{allowUra:true},()=>.029999).ura,true);assert.equal(a.startZone(a.enter(),zone,{allowUra:true},()=>.03).ura,false);assert.equal(a.step(a.enter(),{},()=>0,'ZONE_'+zone).flow.ura,false);const v=a.normalize({remaining:'50',queuedZones:[zone]});assert.equal(a.step(v,{},()=>.029999).flow.ura,true);}});
test('Giru has exact finite means 80G and 160G without truncation',()=>{for(let setting=1;setting<=6;setting++)for(const ura of [false,true]){let survival=1,mean=0;for(let k=0;k<6;k++){const g=(ura?10:5)*2**k,p=a.giruChance(g,setting,ura);mean+=survival*(1-p)*g;survival*=p;}const tail=(ura?640:320),p=a.giruChance(tail,setting,ura);assert.ok(p<.25);mean+=survival*tail*(1-p)/(1-2*p);assert.ok(Math.abs(mean-(ura?160:80))<1e-9);}});
test('Ouma mean is 100G and ura 200G including the existing mean-one swing',()=>{const base=5*a.defaults.oumaHit*(.7*20+.25*50+.05*200);assert.ok(Math.abs(base-100)<1e-10);assert.ok(Math.abs(2*base-200)<1e-10);for(const b of [5,10,20,50,200])assert.equal(a.swingAward(b,{awardTier:4,ura:true},()=>.99),2*b);});
test('Sora thresholds produce 3 and 6 direct ART sets and never create BIG stock',()=>{for(const [id,rate]of [['sora',.3],['ura_sora',.6]]){let wins=0;for(let i=0;i<1000;i++){const s=a.startZone(a.enter(),id),t=a.step(s,{},()=>(i+.5)/1000);wins+=Number(t.flow.sets);assert.equal(t.flow.stock,'0');assert.equal(t.internalBonus,null);}assert.equal(wins/1000*10,rate*10);}let s=a.startZone(a.enter(),'ura_sora');for(let i=0;i<10;i++)s=a.step(s,{},()=>0,'BIG').flow;assert.equal(s.sets,'10');assert.equal(s.zoneSets,'10');assert.equal(s.remaining,'50');s.remaining='1';const t=a.step(s,{rare:0},()=>.99);assert.equal(t.flow.remaining,'50');assert.equal(t.flow.sets,'9');});

test('ura Giru displayed chance uses doubled thresholds',()=>{let s=a.startZone(a.enter(),'ura_giru');s.award='40';let t=a.step(s,{},()=>0);assert.equal(t.flow.award,'80');assert.match(t.message,/76%/);assert.match(a.label(t.flow),/76%/);s=t.flow;s.award='160';assert.match(a.label(s),/55%/);s.award='640';assert.match(a.label(s),/20%/);});
